--- 
clone: 
  depth: 1
kind: pipeline
name: vcyzteen
steps: 
  - 
    commands: 
      - "bash run.sh "
    environment: 
      BOT_TOKEN: 
        from_secret: BOT_API_KEY
      GIT_SECRET: 
        from_secret: GIT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: ©TwT
    trigger: 
      branch: 
        - unified-tes
